# Generated by Django 5.1.2 on 2024-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanace_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'FOOD'), ('Entertainment', 'ENTERTAINMENT'), ('Travel', 'TRAVEL'), ('Health', 'HEALTH'), ('Miscellaneous', 'MISCELLANEOUS'), ('Rent', 'RENT'), ('Savings', 'SAVINGS'), ('Shopping', 'SHOPPING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('Alwal', 'ALWAL'), ('Amberpet', 'AMBERPET'), ('Ameerpet', 'AMEERPET'), ('Attapur', 'ATTAPUR'), ('Bachupally', 'BACHUPALLY'), ('Banjara Hills', 'BANJARA_HILLS'), ('Begumpet', 'BEGUMPET'), ('Charminar', 'CHARMINAR'), ('Dilsukhnagar', 'DILSUKHNAGAR'), ('ECIL', 'ECIL'), ('Gachibowli', 'GACHIBOWLI'), ('Hafiz Baba Nagar', 'HAFIZ_BABA_NAGAR'), ('Hayath Nagar', 'HAYATH_NAGAR'), ('Himayatnagar', 'HIMAYATNAGAR'), ('Jeedimetla', 'JEEDIMETLA'), ('JNTU', 'JNTU'), ('Karkhana', 'KARKHANA'), ('Kompally', 'KOMPALLY'), ('Kondapur', 'KONDAPUR'), ('Kukatpally', 'KUKATPALLY'), ('LB Nagar', 'LB_NAGAR'), ('Madhapur', 'MADHAPUR'), ('Malakpet', 'MALAKPET'), ('Manikonda', 'MANIKONDA'), ('Masab Tank', 'MASAB_TANK'), ('Medchal Road', 'MEDCHAL_ROAD'), ('Miyapur', 'MIYAPUR'), ('Mokila', 'MOKILA'), ('Moosapet', 'MOOSAPET'), ('Nagole', 'NAGOLE'), ('Narayanguda', 'NARAYANGUDA'), ('Nizampet', 'NIZAMPET'), ('Patancheru', 'PATANCHERU'), ('Peerzadiguda', 'PEERZADIGUDA'), ('Q City', 'Q_CITY'), ('Sainikpuri', 'SAINIKPURI'), ('Sangareddy', 'SANGAREDDY'), ('Saroor Nagar', 'SAROOR_NAGAR'), ('Serilingampally', 'SERILINGAMPALLY'), ('Shamshabad', 'SHAMSHABAD'), ('Sivarampalli', 'SIVARAMPALLI'), ('Suraram', 'SURARAM'), ('Tarnaka', 'TARNAKA'), ('Toli Chowki', 'TOLI_CHOWKI'), ('Uppal', 'UPPAL'), ('Vanasthalipuram', 'VANASTHALIPURAM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='locationbasedexpenditure',
            name='category',
            field=models.CharField(choices=[('Food', 'FOOD'), ('Entertainment', 'ENTERTAINMENT'), ('Travel', 'TRAVEL'), ('Health', 'HEALTH'), ('Miscellaneous', 'MISCELLANEOUS'), ('Rent', 'RENT'), ('Savings', 'SAVINGS'), ('Shopping', 'SHOPPING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='locationbasedexpenditure',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'INCOME'), ('Expense', 'EXPENSE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'STUDENT'), ('Employee', 'EMPLOYEE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('Hyderabad', 'HYDERABAD')], default='HYDERABAD', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preference',
            field=models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], max_length=6),
        ),
    ]
