# Generated by Django 5.0.6 on 2024-10-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanace_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationbasedexpenditure',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('TRAVEL', 'Travel'), ('HEALTH', 'Health'), ('MISCELLANEOUS', 'Miscellaneous'), ('RENT', 'Rent'), ('SAVINGS', 'Savings'), ('SHOPPING', 'Shopping')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ExpenditureCategory',
        ),
    ]
