# Generated by Django 5.0.6 on 2024-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanace_backend', '0002_alter_locationbasedexpenditure_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('ALWAL', 'Alwal'), ('AMBERPET', 'Amberpet'), ('AMEERPET', 'Ameerpet'), ('ATTAPUR', 'Attapur'), ('BACHUPALLY', 'Bachupally'), ('BANJARA_HILLS', 'Banjara Hills'), ('BEGUMPET', 'Begumpet'), ('CHARMINAR', 'Charminar'), ('DILSUKHNAGAR', 'Dilsukhnagar'), ('ECIL', 'ECIL'), ('GACHIBOWLI', 'Gachibowli'), ('HAFIZ_BABA_NAGAR', 'Hafiz Baba Nagar'), ('HAYATH_NAGAR', 'Hayath Nagar'), ('HIMAYATNAGAR', 'Himayatnagar'), ('JEEDIMETLA', 'Jeedimetla'), ('JNTU', 'JNTU'), ('KARKHANA', 'Karkhana'), ('KOMPALLY', 'Kompally'), ('KONDAPUR', 'Kondapur'), ('KUKATPALLY', 'Kukatpally'), ('LB_NAGAR', 'LB Nagar'), ('MADHAPUR', 'Madhapur'), ('MALAKPET', 'Malakpet'), ('MANIKONDA', 'Manikonda'), ('MASAB_TANK', 'Masab Tank'), ('MEDCHAL_ROAD', 'Medchal Road'), ('MIYAPUR', 'Miyapur'), ('MOKILA', 'Mokila'), ('MOOSAPET', 'Moosapet'), ('NAGOLE', 'Nagole'), ('NARAYANGUDA', 'Narayanguda'), ('NIZAMPET', 'Nizampet'), ('PATANCHERU', 'Patancheru'), ('PEERZADIGUDA', 'Peerzadiguda'), ('Q_CITY', 'Q City'), ('SAINIKPURI', 'Sainikpuri'), ('SANGAREDDY', 'Sangareddy'), ('SAROOR_NAGAR', 'Saroor Nagar'), ('SERILINGAMPALLY', 'Serilingampally'), ('SHAMSHABAD', 'Shamshabad'), ('SIVARAMPALLI', 'Sivarampalli'), ('SURARAM', 'Suraram'), ('TARNAKA', 'Tarnaka'), ('TOLI_CHOWKI', 'Toli Chowki'), ('UPPAL', 'Uppal'), ('VANASTHALIPURAM', 'Vanasthalipuram')], max_length=50, unique=True),
        ),
    ]
