# Generated by Django 5.0.6 on 2024-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanace_backend', '0003_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Hyderabad', max_length=150),
        ),
    ]
