# Generated by Django 5.0.6 on 2024-10-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanace_backend', '0005_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('hyderabad', 'Hyderabad')], default='hyderabad', max_length=150),
        ),
    ]
